name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          # Built-in pip cache (keyed by the files below)
          cache: "pip"
          cache-dependency-path: |
            requirements-dev.txt
            requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          # Ensure linters are present even if not listed in requirements-dev
          pip install -q "pylint>=3.2" "pylint-exit>=1.2.0"

      - name: Pylint (src + tests)
        run: |
          python -m pylint $(git ls-files '*.py') || python -m pylint_exit $?

      - name: Pytest (fast)
        env:
          AWS_ACCESS_KEY_ID: fake
          AWS_SECRET_ACCESS_KEY: fake
          AWS_SESSION_TOKEN: fake
          AWS_DEFAULT_REGION: us-east-1
          AWS_EC2_METADATA_DISABLED: "true"
        run: |
          pytest -q

      # Optional: moto-based integration tests (runs only on push)
      - name: Pytest (integration with moto)
        if: ${{ github.event_name == 'push' }}
        env:
          AWS_ACCESS_KEY_ID: fake
          AWS_SECRET_ACCESS_KEY: fake
          AWS_SESSION_TOKEN: fake
          AWS_DEFAULT_REGION: us-east-1
          AWS_EC2_METADATA_DISABLED: "true"
        run: |
          pytest -q -m integration
