name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Pylint (src + tests)
        run: |
          python -m pylint $(git ls-files '*.py') || python -m pylint_exit $?

      - name: Pytest (fast)
        env:
          AWS_ACCESS_KEY_ID: fake
          AWS_SECRET_ACCESS_KEY: fake
          AWS_SESSION_TOKEN: fake
          AWS_DEFAULT_REGION: us-east-1
          AWS_EC2_METADATA_DISABLED: "true"
        run: |
          pytest -q

      # Optional: enable moto-based integration tests
      - name: Pytest (integration with moto)
        if: ${{ github.event_name == 'push' }}  # or nightly, or a separate workflow
        env:
          AWS_ACCESS_KEY_ID: fake
          AWS_SECRET_ACCESS_KEY: fake
          AWS_SESSION_TOKEN: fake
          AWS_DEFAULT_REGION: us-east-1
          AWS_EC2_METADATA_DISABLED: "true"
        run: |
          pytest -q -m integration