name: Tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # test/dev deps (adjust as your tests need)
          pip install pytest pytest-cov moto[boto3] boto3-stubs[ec2,iam,s3,cloudwatch,logs,pricing] types-requests

      - name: Run tests
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_EC2_METADATA_DISABLED: "true"  # avoid IMDS calls
        run: |
          pytest PYTHONPATH=$PWD -q --maxfail=1 --cov=finops_toolset --cov-report=xml

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml
